name: Deploy Python project to Azure Function App

on:
  push:
    branches:
      - main  # Deploy only when pushing to the 'main' branch

env:
  AZURE_FUNCTIONAPP_NAME: 'Lead-Gerarator-UAT'
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.' # Path to your function app project
  PYTHON_VERSION: '3.11'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: main
    permissions:
      contents: read # Required for actions/checkout

    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4

    - name: Setup Python ${{ env.PYTHON_VERSION }} Environment
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install system dependencies for Playwright
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libwoff1 \
          libvpx9 \
          libopus0 \
          libgstreamer-plugins-base1.0-0 \
          libgstreamer1.0-0 \
          libharfbuzz-icu0 \
          libhyphen0 \
          libmanette-0.2-0 \
          libflite1 \
          libsecret-1-0 \
          libavif16 \
          libgl1-mesa-dri \
          libegl1 \
          libgles2 \
          libevent-2.1-7 \
          libgtk-4-1 \
          libgraphene-1.0-0 \
          libgstreamer-gl1.0-0 \
          libgstreamer-plugins-bad1.0-0 \
          libx264-dev \
          libnspr4 \
          libnss3 \
          libdbus-glib-1-2 \
          libpango-1.0-0 \
          libpangocairo-1.0-0 \
          libatk1.0-0 \
          libatk-bridge2.0-0 \
          libcups2 \
          libdrm2 \
          libxcomposite1 \
          libxdamage1 \
          libxfixes3 \
          libxrandr2 \
          libgbm1 \
          libasound2t64

    - name: Install Python Dependencies and Playwright Browsers
      shell: bash
      run: |
        echo "Installing Python dependencies and Playwright browsers..."
        
        # Upgrade pip
        python -m pip install --upgrade pip
        
        # Install all Python dependencies, including playwright, into the designated folder
        pip install -r requirements.txt --target="${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/.python_packages/lib/site-packages"

        # Set environment variable to ensure browsers are installed to the correct, deployed folder
        export PLAYWRIGHT_BROWSERS_PATH="${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/.playwright-browsers"

        # Install Playwright browsers for the Linux environment
        python -m playwright install --with-deps chromium
        
        echo "Playwright browsers installed to: $PLAYWRIGHT_BROWSERS_PATH"

    - name: 'Deploy to Azure Functions'
      uses: Azure/functions-action@v1
      id: deploy-to-function
      with:
        app-name: 'Lead-Gerarator-UAT'
        slot-name: 'Production'
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_5AED830D9F4A460397BA9ECCE14CE145 }}
        sku: 'flexconsumption'
        # Crucial: Set these to false because we pre-packaged everything above
        scm-do-build-during-deployment: false
        enable-oryx-build: false
