# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure Functions: https://aka.ms/python-webapps-actions

name: Build and deploy Python project to Azure Function App - Lead-Gerarator-UAT

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: 'Lead-Generator-UAT'
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.' # set this to the path to your web app project, defaults to the repository root
  PYTHON_VERSION: '3.11' # set this to the python version to use (supports 3.6, 3.7, 3.8)

jobs:
  build:
    runs-on: ubuntu-latest
    environment: main

    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4

    - name: Setup Python ${{ env.PYTHON_VERSION }} Environment
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install system dependencies for Playwright
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libwoff1 \
          libvpx9 \
          libopus0 \
          libgstreamer-plugins-base1.0-0 \
          libgstreamer1.0-0 \
          libharfbuzz-icu0 \
          libhyphen0 \
          libmanette-0.2-0 \
          libflite1 \
          libsecret-1-0 \
          libavif16 \
          libgl1-mesa-dri \
          libegl1 \
          libgles2 \
          libevent-2.1-7 \
          libgtk-4-1 \
          libgraphene-1.0-0 \
          libgstreamer-gl1.0-0 \
          libgstreamer-plugins-bad1.0-0 \
          libx264-dev
    permissions:
      contents: read #This is required for actions/checkout

        - name: Install Python Dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt --target=".python_packages/lib/site-packages"

    - name: Install Playwright (Python)
      run: |
        python -m pip install playwright
        echo "Playwright Installed."

    - name: Make `startup.sh` Executable
      run: chmod +x startup.sh

    - name: Execute `startup.sh` to Install Playwright Browsers
      run: ./startup.sh

    - name: Verify Playwright Installation
      run: |
        python -c "from playwright.sync_api import sync_playwright; print('Playwright is working!' if sync_playwright() else 'Failed')"

    - name: Package `.playwright-browsers` for Deployment
      run: |
        mkdir -p ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/.playwright-browsers
        cp -r /home/runner/.playwright-browsers/* ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/.playwright-browsers/
        echo "Packaged Playwright Browsers."

    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
        scm-do-build-during-deployment: true
        enable-oryx-build: true
        

